# BIBLIOTECAS

In [19]:
import pandas as pd
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# LEITURA DOS DADOS

In [21]:
url = 'https://raw.githubusercontent.com/RyanXHF/ml_finished_projects/main/Customer-Churn.csv'  # Use raw content URL
db = pd.read_csv(url)
db

,Maior65Anos,Conjuge,Dependentes,MesesDeContrato,TelefoneFixo,VariasLinhasTelefonicas,ServicoDeInternet,SegurancaOnline,BackupOnline,SeguroNoDispositivo,SuporteTecnico,TVaCabo,StreamingDeFilmes,TipoDeContrato,PagamentoOnline,FormaDePagamento,ContaMensal,Churn
0,0,Sim,Nao,1,Nao,SemServicoTelefonico,DSL,Nao,Sim,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequeDigital,29.85,Nao
1,0,Nao,Nao,34,Sim,Nao,DSL,Sim,Nao,Sim,Nao,Nao,Nao,UmAno,Nao,ChequePapel,56.95,Nao
2,0,Nao,Nao,2,Sim,Nao,DSL,Sim,Sim,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequePapel,53.85,Sim
3,0,Nao,Nao,45,Nao,SemServicoTelefonico,DSL,Sim,Nao,Sim,Sim,Nao,Nao,UmAno,Nao,DebitoEmConta,42.30,Nao
4,0,Nao,Nao,2,Sim,Nao,FibraOptica,Nao,Nao,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequeDigital,70.70,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,Sim,Sim,24,Sim,Sim,DSL,Sim,Nao,Sim,Sim,Sim,Sim,UmAno,Sim,ChequePapel,84.80,Nao
7039,0,Sim,Sim,72,Sim,Sim,FibraOptica,Nao,Sim,Sim,Nao,Sim,Sim,UmAno,Sim,CartaoDeCredito,103.20,Nao
7040,0,Sim,Sim,11,Nao,SemServicoTelefonico,DSL,Sim,Nao,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequeDigital,29.60,Nao
7041,1,Sim,Nao,4,Sim,Sim,FibraOptica,Nao,Nao,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequePapel,74.40,Sim
7042,0,Nao,Nao,66,Sim,Nao,FibraOptica,Sim,Nao,Sim,Sim,Sim,Sim,DoisAnos,Sim,DebitoEmConta,105.65,Nao

## RENOMEANDO COLUNAS

In [22]:
troca = {'Nao': 0,
         'Sim': 1} # converte sim/nao em 1/0

db['Churn'] = db.Churn.map(troca) # realiza a conversão sim/nao em 1/0
db

,Maior65Anos,Conjuge,Dependentes,MesesDeContrato,TelefoneFixo,VariasLinhasTelefonicas,ServicoDeInternet,SegurancaOnline,BackupOnline,SeguroNoDispositivo,SuporteTecnico,TVaCabo,StreamingDeFilmes,TipoDeContrato,PagamentoOnline,FormaDePagamento,ContaMensal,Churn
0,0,Sim,Nao,1,Nao,SemServicoTelefonico,DSL,Nao,Sim,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequeDigital,29.85,0
1,0,Nao,Nao,34,Sim,Nao,DSL,Sim,Nao,Sim,Nao,Nao,Nao,UmAno,Nao,ChequePapel,56.95,0
2,0,Nao,Nao,2,Sim,Nao,DSL,Sim,Sim,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequePapel,53.85,1
3,0,Nao,Nao,45,Nao,SemServicoTelefonico,DSL,Sim,Nao,Sim,Sim,Nao,Nao,UmAno,Nao,DebitoEmConta,42.30,0
4,0,Nao,Nao,2,Sim,Nao,FibraOptica,Nao,Nao,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequeDigital,70.70,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,Sim,Sim,24,Sim,Sim,DSL,Sim,Nao,Sim,Sim,Sim,Sim,UmAno,Sim,ChequePapel,84.80,0
7039,0,Sim,Sim,72,Sim,Sim,FibraOptica,Nao,Sim,Sim,Nao,Sim,Sim,UmAno,Sim,CartaoDeCredito,103.20,0
7040,0,Sim,Sim,11,Nao,SemServicoTelefonico,DSL,Sim,Nao,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequeDigital,29.60,0
7041,1,Sim,Nao,4,Sim,Sim,FibraOptica,Nao,Nao,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequePapel,74.40,1
7042,0,Nao,Nao,66,Sim,Nao,FibraOptica,Sim,Nao,Sim,Sim,Sim,Sim,DoisAnos,Sim,DebitoEmConta,105.65,0

In [27]:
x = db[['Maior65Anos', 'Conjuge', 'Dependentes', 'MesesDeContrato', "TelefoneFixo",
        "VariasLinhasTelefonicas",	"ServicoDeInternet",	"SegurancaOnline",	"BackupOnline",
        "SeguroNoDispositivo",	"SuporteTecnico",	"TVaCabo",	"StreamingDeFilmes",
        "TipoDeContrato", "PagamentoOnline",	"FormaDePagamento",	"ContaMensal"]]	# Features

x

,Maior65Anos,Conjuge,Dependentes,MesesDeContrato,TelefoneFixo,VariasLinhasTelefonicas,ServicoDeInternet,SegurancaOnline,BackupOnline,SeguroNoDispositivo,SuporteTecnico,TVaCabo,StreamingDeFilmes,TipoDeContrato,PagamentoOnline,FormaDePagamento,ContaMensal
0,0,Sim,Nao,1,Nao,SemServicoTelefonico,DSL,Nao,Sim,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequeDigital,29.85
1,0,Nao,Nao,34,Sim,Nao,DSL,Sim,Nao,Sim,Nao,Nao,Nao,UmAno,Nao,ChequePapel,56.95
2,0,Nao,Nao,2,Sim,Nao,DSL,Sim,Sim,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequePapel,53.85
3,0,Nao,Nao,45,Nao,SemServicoTelefonico,DSL,Sim,Nao,Sim,Sim,Nao,Nao,UmAno,Nao,DebitoEmConta,42.30
4,0,Nao,Nao,2,Sim,Nao,FibraOptica,Nao,Nao,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequeDigital,70.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,Sim,Sim,24,Sim,Sim,DSL,Sim,Nao,Sim,Sim,Sim,Sim,UmAno,Sim,ChequePapel,84.80
7039,0,Sim,Sim,72,Sim,Sim,FibraOptica,Nao,Sim,Sim,Nao,Sim,Sim,UmAno,Sim,CartaoDeCredito,103.20
7040,0,Sim,Sim,11,Nao,SemServicoTelefonico,DSL,Sim,Nao,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequeDigital,29.60
7041,1,Sim,Nao,4,Sim,Sim,FibraOptica,Nao,Nao,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequePapel,74.40
7042,0,Nao,Nao,66,Sim,Nao,FibraOptica,Sim,Nao,Sim,Sim,Sim,Sim,DoisAnos,Sim,DebitoEmConta,105.65

In [26]:
y = db["Churn"] # Classes
y

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

# SELEÇÃO DOS DADOS PARA TREINO

CLASSIFICAÇÃO BINARIA
* CLASSES (Y) -> bought(1/0) -> CLASSIFICAÇÃO BINARIA
* FEATURE NÃO DEFINE SE CLASSE É BINARIA

- CONSTRUÇÃO DO MODELO MACHINE LEARNING
   * TREINO 75% DADOS -> FIT
   * TESTE 25% -> ACURACIA

In [40]:
# Separar treino e teste
seed = 20
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.25, random_state=seed, stratify=y)

print('Treinamento com %d elementos e testarmos com %d elementos' % (len(train_x), len(test_x)))

Treinamento com 5282 elementos e testarmos com 1761 elementos

### MODELO CLASSIFICADOR

In [41]:
# Import necessary library
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Iterate through columns of train_x and test_x and encode string columns
for col in train_x.columns:
    if train_x[col].dtype == 'object':
        train_x[col] = label_encoder.fit_transform(train_x[col])
        test_x[col] = label_encoder.transform(test_x[col]) # Use the same encoder to transform test_x


model = LinearSVC() # Cria o modelo
model.fit(train_x, train_y) # treino

result = model.predict(test_x) # teste

acuracia = accuracy_score(test_y, result) # compara vetores
acuracia_model = model.score(test_x, test_y) # roda teste

print("Acuracia: ", (acuracia*100), "%")
print("Acuracia_model: ", (acuracia_model*100), "%")

Acuracia:  63.37308347529813 %
Acuracia_model:  63.37308347529813 %

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

### DUMMY (BASELINE)

In [42]:
from sklearn.dummy import DummyClassifier

dummy_stratified = DummyClassifier()
dummy_stratified.fit(train_x, train_y)
acuracia_dummy = dummy_stratified.score(test_x, test_y)

print("Acuracia Dummy: ", (acuracia_dummy*100), "%")

Acuracia Dummy:  73.480976717774 %