# BIBLIOTECAS

In [ ]:
import pandas as pd
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# LEITURA DOS DADOS

In [ ]:
url = 'https://raw.githubusercontent.com/RyanXHF/ml_finished_projects/main/car-prices.csv'  # Use raw content URL
db = pd.read_csv(url)
db

      Unnamed: 0  mileage_per_year  model_year      price sold
0              0             21801        2000   30941.02  yes
1              1              7843        1998   40557.96  yes
2              2              7109        2006   89627.50   no
3              3             26823        2015   95276.14   no
4              4              7935        2014  117384.68  yes
...          ...               ...         ...        ...  ...
9995        9995             15572        2006   97112.86   no
9996        9996             13246        2002  107424.63  yes
9997        9997             13018        2014   93856.99   no
9998        9998             10464        2011   51250.57  yes
9999        9999             12362        1999   87945.73   no

[10000 rows x 5 columns]

## RENOMEANDO COLUNAS

In [ ]:
mapa = {"mileage_per_year": "km_por_ano",
        "model_year": "ano_do_modelo",
        "price": "preco",
        "sold": "vendido"}

db = db.rename(columns=mapa)
db

      Unnamed: 0  km_por_ano  ano_do_modelo      preco vendido
0              0       21801           2000   30941.02     yes
1              1        7843           1998   40557.96     yes
2              2        7109           2006   89627.50      no
3              3       26823           2015   95276.14      no
4              4        7935           2014  117384.68     yes
...          ...         ...            ...        ...     ...
9995        9995       15572           2006   97112.86      no
9996        9996       13246           2002  107424.63     yes
9997        9997       13018           2014   93856.99      no
9998        9998       10464           2011   51250.57     yes
9999        9999       12362           1999   87945.73      no

[10000 rows x 5 columns]

In [ ]:
db["km_por_ano"] = db.km_por_ano * 1.60934 # converte milhas em km
troca = {'yes': 1,
         'no': 0} # converte sim/nao em 1/0

db['vendido'] = db.vendido.map(troca) # realiza a conversão sim/nao em 1/0
db

      Unnamed: 0   km_por_ano  ano_do_modelo      preco  vendido
0              0  35085.22134           2000   30941.02        1
1              1  12622.05362           1998   40557.96        1
2              2  11440.79806           2006   89627.50        0
3              3  43167.32682           2015   95276.14        0
4              4  12770.11290           2014  117384.68        1
...          ...          ...            ...        ...      ...
9995        9995  25060.64248           2006   97112.86        0
9996        9996  21317.31764           2002  107424.63        1
9997        9997  20950.38812           2014   93856.99        0
9998        9998  16840.13376           2011   51250.57        1
9999        9999  19894.66108           1999   87945.73        0

[10000 rows x 5 columns]

In [ ]:
x = db[["km_por_ano","ano_do_modelo","preco"]] # Features
x

       km_por_ano  ano_do_modelo      preco
0     35085.22134           2000   30941.02
1     12622.05362           1998   40557.96
2     11440.79806           2006   89627.50
3     43167.32682           2015   95276.14
4     12770.11290           2014  117384.68
...           ...            ...        ...
9995  25060.64248           2006   97112.86
9996  21317.31764           2002  107424.63
9997  20950.38812           2014   93856.99
9998  16840.13376           2011   51250.57
9999  19894.66108           1999   87945.73

[10000 rows x 3 columns]

In [ ]:
y = db["vendido"] # Classes
y

0       1
1       1
2       0
3       0
4       1
       ..
9995    0
9996    1
9997    0
9998    1
9999    0
Name: vendido, Length: 10000, dtype: int64

# SELEÇÃO DOS DADOS PARA TREINO

CLASSIFICAÇÃO BINARIA
* CLASSES (Y) -> bought(1/0) -> CLASSIFICAÇÃO BINARIA
* FEATURE NÃO DEFINE SE CLASSE É BINARIA

- CONSTRUÇÃO DO MODELO MACHINE LEARNING
   * TREINO 75% DADOS -> FIT
   * TESTE 25% -> ACURACIA

In [ ]:
# Separar treino e teste
seed = 42
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.25, random_state=seed, stratify=y)

print('Treinamento com %d elementos e testarmos com %d elementos' % (len(train_x), len(test_x)))

Treinamento com 7500 elementos e testarmos com 2500 elementos

### MODELO CLASSIFICADOR

In [ ]:
model = LinearSVC() # Cria o modelo
model.fit(train_x, train_y) # treino

result = model.predict(test_x) # teste

acuracia = accuracy_score(test_y, result) # compara vetores
acuracia_model = model.score(test_x, test_y) # roda teste

print("Acuracia: ", (acuracia*100), "%")
print("Acuracia_model: ", (acuracia_model*100), "%")

Acuracia:  66.60000000000001 %
Acuracia_model:  66.60000000000001 %

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

### DUMMY (BASELINE)

In [ ]:
from sklearn.dummy import DummyClassifier

dummy_stratified = DummyClassifier()
dummy_stratified.fit(train_x, train_y)
acuracia_dummy = dummy_stratified.score(test_x, test_y)

print("Acuracia Dummy: ", (acuracia_dummy*100), "%")

Acuracia Dummy:  57.99999999999999 %