# BIBLIOTECAS

In [8]:
import pandas as pd
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# LEITURA DOS DADOS

In [22]:
url = 'https://raw.githubusercontent.com/RyanXHF/ml_finished_projects/main/projects.csv'  # Use raw content URL
db = pd.read_csv(url)
db

      unfinished  expected_hours  price
0              1              26    192
1              1              88   9015
2              1              89   2577
3              1              42    275
4              1              39    170
...          ...             ...    ...
2152           0              80   7518
2153           1              52   1332
2154           0              40    473
2155           0              75   5324
2156           1              37    377

[2157 rows x 3 columns]

## RENOMEANDO COLUNAS

In [16]:
mapa = {"unfinished": "finalizado", "expected_hours": "horas_esperadas", "price": "preco"}

db = db.rename(columns=mapa)
db

      finalizado  horas_esperadas  preco
0              0               26    192
1              0               88   9015
2              0               89   2577
3              0               42    275
4              0               39    170
...          ...              ...    ...
2152           1               80   7518
2153           0               52   1332
2154           1               40    473
2155           1               75   5324
2156           0               37    377

[2157 rows x 3 columns]

In [12]:
troca = {1: 0,
         0: 1}

db['finalizado'] = db.finalizado.map(troca)
db

      finalizado  horas_esperadas  preco
0              0               26    192
1              0               88   9015
2              0               89   2577
3              0               42    275
4              0               39    170
...          ...              ...    ...
2152           1               80   7518
2153           0               52   1332
2154           1               40    473
2155           1               75   5324
2156           0               37    377

[2157 rows x 3 columns]

In [17]:
x = db[["horas_esperadas","preco"]] # Features
x

      horas_esperadas  preco
0                  26    192
1                  88   9015
2                  89   2577
3                  42    275
4                  39    170
...               ...    ...
2152               80   7518
2153               52   1332
2154               40    473
2155               75   5324
2156               37    377

[2157 rows x 2 columns]

In [18]:
y = db["finalizado"] # Classes
y

0       0
1       0
2       0
3       0
4       0
       ..
2152    1
2153    0
2154    1
2155    1
2156    0
Name: finalizado, Length: 2157, dtype: int64

# SELEÇÃO DOS DADOS PARA TREINO

CLASSIFICAÇÃO BINARIA
* CLASSES (Y) -> bought(1/0) -> CLASSIFICAÇÃO BINARIA
* FEATURE NÃO DEFINE SE CLASSE É BINARIA

- CONSTRUÇÃO DO MODELO MACHINE LEARNING
   * TREINO 75% DADOS -> FIT
   * TESTE 25% -> ACURACIA

In [19]:
# Separar treino e teste
seed = 42
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.25, random_state=seed, stratify=y)

print('Treinamento com %d elementos e testarmos com %d elementos' % (len(train_x), len(test_x)))

Treinamento com 1617 elementos e testarmos com 540 elementos

### MODELO CLASSIFICADOR

In [20]:
model = LinearSVC() # Cria o modelo
model.fit(train_x, train_y) # treino

result = model.predict(test_x) # teste

acuracia = accuracy_score(test_y, result) # compara vetores
acuracia_model = model.score(test_x, test_y) # roda teste

print("Acuracia: ", (acuracia*100), "%")
print("Acuracia_model: ", (acuracia_model*100), "%")

Acuracia:  63.51851851851852 %
Acuracia_model:  63.51851851851852 %

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

### DUMMY (BASELINE)

In [21]:
from sklearn.dummy import DummyClassifier

dummy_stratified = DummyClassifier()
dummy_stratified.fit(train_x, train_y)
acuracia_dummy = dummy_stratified.score(test_x, test_y)

print("Acuracia Dummy: ", (acuracia_dummy*100), "%")

Acuracia Dummy:  52.59259259259259 %