# BIBLIOTECAS

In [62]:
import pandas as pd
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# LEITURA DOS DADOS

In [63]:
url = 'https://raw.githubusercontent.com/RyanXHF/ml_finished_projects/main/tracking.csv'  # Updated URL to access raw content
db = pd.read_csv(url)
db

    home  how_it_works  contact  bought
0      1             1        0       0
1      1             1        0       0
2      1             1        0       0
3      1             1        0       0
4      1             1        0       0
..   ...           ...      ...     ...
94     0             0        1       0
95     1             1        1       1
96     0             0        1       0
97     0             1        0       0
98     0             0        0       0

[99 rows x 4 columns]

RENOMEANDO COLUNAS

In [64]:
mapa = {"home": "principal",
        "how_it_works": "como_funciona",
        "contact": "contato",
        "bought": "comprou"}

db = db.rename(columns=mapa)
db

    principal  como_funciona  contato  comprou
0           1              1        0        0
1           1              1        0        0
2           1              1        0        0
3           1              1        0        0
4           1              1        0        0
..        ...            ...      ...      ...
94          0              0        1        0
95          1              1        1        1
96          0              0        1        0
97          0              1        0        0
98          0              0        0        0

[99 rows x 4 columns]

In [65]:
x = db[["principal","como_funciona","contato"]] # Features
x

    principal  como_funciona  contato
0           1              1        0
1           1              1        0
2           1              1        0
3           1              1        0
4           1              1        0
..        ...            ...      ...
94          0              0        1
95          1              1        1
96          0              0        1
97          0              1        0
98          0              0        0

[99 rows x 3 columns]

In [66]:
y = db["comprou"] # Classes
y

0     0
1     0
2     0
3     0
4     0
     ..
94    0
95    1
96    0
97    0
98    0
Name: comprou, Length: 99, dtype: int64

# SELEÇÃO DOS DADOS PARA TREINO

## CLASSIFICAÇÃO BINARIA

* CLASSES (Y) -> bought(1/0) -> CLASSIFICAÇÃO BINARIA
* FEATURE NÃO DEFINE SE CLASSE É BINARIA

- CONSTRUÇÃO DO MODELO MACHINE LEARNING
   * TREINO 75% DADOS -> FIT
   * TESTE 25% -> ACURACIA

In [67]:
train_x = x[:75]
test_x = x[75:]

train_y = y[:75]
test_y = y[75:]

print('Treinamento com %d elementos e testarmos com %d elementos' % (len(train_x), len(test_x)))

model = LinearSVC() # Cria o modelo
model.fit(train_x, train_y) # treino

result = model.predict(test_x) # teste

acuracia = accuracy_score(test_y, result) # compara vetores
acuracia_model = model.score(test_x, test_y) # roda teste

print("Acuracia: ", (acuracia*100), "%")
print("Acuracia_model: ", (acuracia_model*100), "%")

Treinamento com 75 elementos e testarmos com 24 elementos
Acuracia:  95.83333333333334 %
Acuracia_model:  95.83333333333334 %

In [68]:
values = [[1,0,0], [1,1,0], [1,0,1], [0,1,1]]
result_values = model.predict(values)
print(result_values)

[0 0 1 0]

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearSVC was fitted with feature names
  warnings.warn(

## SEPARAÇÃO DO TREINO E TESTE

In [69]:
# Separar treino e teste
seed = 42
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.25, random_state=seed)

print('Treinamento com %d elementos e testarmos com %d elementos' % (len(train_x), len(test_x)))

Treinamento com 74 elementos e testarmos com 25 elementos

### MODELO CLASSIFICADOR

In [70]:
model = LinearSVC() # Cria o modelo
model.fit(train_x, train_y) # treino

result = model.predict(test_x) # teste

acuracia = accuracy_score(test_y, result) # compara vetores
acuracia_model = model.score(test_x, test_y) # roda teste

print("Acuracia: ", (acuracia*100), "%")
print("Acuracia_model: ", (acuracia_model*100), "%")

Acuracia:  96.0 %
Acuracia_model:  96.0 %

### COMPARAÇÃO ACURACIA DUMMY (BASELINE)

In [71]:
from sklearn.dummy import DummyClassifier

dummy_stratified = DummyClassifier()
dummy_stratified.fit(train_x, train_y)
acuracia_dummy = dummy_stratified.score(test_x, test_y)

print("Acuracia Dummy: ", (acuracia_dummy*100), "%")

Acuracia Dummy:  64.0 %

In [72]:
test_y.value_counts()

comprou
0    16
1     9
Name: count, dtype: int64

## VERIFICAÇÃO DA PROPORÇÃO TREINO E TESTE

In [73]:
# Separar treino e teste
seed = 42
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.25, random_state=seed, stratify=y)

print('Treinamento com %d elementos e testarmos com %d elementos' % (len(train_x), len(test_x)))

Treinamento com 74 elementos e testarmos com 25 elementos

### MODELO CLASSIFICADOR

In [74]:
model = LinearSVC() # Cria o modelo
model.fit(train_x, train_y) # treino

result = model.predict(test_x) # teste

acuracia = accuracy_score(test_y, result) # compara vetores
acuracia_model = model.score(test_x, test_y) # roda teste

print("Acuracia: ", (acuracia*100), "%")
print("Acuracia_model: ", (acuracia_model*100), "%")

Acuracia:  96.0 %
Acuracia_model:  96.0 %

### DUMMY (BASELINE)

In [75]:
from sklearn.dummy import DummyClassifier

dummy_stratified = DummyClassifier()
dummy_stratified.fit(train_x, train_y)
acuracia_dummy = dummy_stratified.score(test_x, test_y)

print("Acuracia Dummy: ", (acuracia_dummy*100), "%")

Acuracia Dummy:  68.0 %